COMMON_MODULES:
  CUSTOM_MESSAGE : "%1$s"
  APPLICATION_ERROR: "An error occurred while processing your request. Please try again later."
  ATOMIC_OPERATION_ERROR: "Atomic operation failed. Rolled back %1$s successful operations. %2$s errors occurred."
  NON_ATOMIC_OPERATION_ERROR: "Operation encountered %1$s errors. %2$s successful operations were completed."
  OBJECT_REQUIRED: "The required object is missing."
  OBJECT_NOT_FOUND: "The requested object was not found."
  ID_REQUIRED: "The ID is required."
  INTERNET_IS_SLOW: "The internet connection is slow. Please try again later."
  FIELD_MISSING : "The field '%1$s' is missing."
  DUPLICATE_FIELD : "The record '%1$s' already exists."

USER_MODULES:
  USER_NOT_FOUND: "We couldnâ€™t find an account with that user ID : '%1$s'. Please check and try again."
  ROLE_NOT_FOUND : "Please select a valid role for the user."
  INCORRECT_PASSWORD: "The password you entered is incorrect. Please try again or reset your password."
  USER_ID_OR_PASSWORD_INCORRECT: "Invalid user ID or password. Please check your credentials and try again."
  ACCOUNT_DISABLED : "Your account has been disabled. Please contact support Team."
  ACCOUNT_LOCKED: "Your account has been locked,Please contact support Team."
  PASSWORD_EXPIRED: "Your password has expired. Please reset your password to continue."
  USER_NOT_AUTHORIZED : "You do not have the necessary permissions to access this resource."
  ROLE_NOT_SELECTED : "No role has been selected for the user."
  LOGOUT_SUCCESS : "You have been successfully logged out."
  PASSWORD_RESET_INITIATED : "A password reset link has been sent to your registered email address."
