COMMON_MODULES:
  CUSTOM_MESSAGE : "%1$s"
  APPLICATION_ERROR: "An error occurred while processing your request. Please try again later."
  ATOMIC_OPERATION_ERROR: "Atomic operation failed. Rolled back %1$s successful operations. %2$s errors occurred."
  NON_ATOMIC_OPERATION_ERROR: "Operation encountered %1$s errors. %2$s successful operations were completed."
  OBJECT_REQUIRED: "The required object is missing."
  OBJECT_NOT_FOUND: "The requested object was not found."
  ID_REQUIRED: "The ID is required."
  INTERNET_IS_SLOW: "The internet connection is slow. Please try again later."
  FIELD_MISSING : "The field '%1$s' is missing."
  REFERENCE_ERROR : "The record cannot be deleted because it is referenced by other records."
  DUPLICATE_RECORD : "A record with the same value already exists."
  DUPLICATE_FIELD : "The record '%1$s' already exists."
  CODE_ALREADY_EXISTS : "The code '%1$s' is already in use. Please choose a different code."
  ERROR_VALIDATING_CODE : "Error while validating the code."
  CODE_REQUIRED : "The code field is required."
  ERROR_VALIDATING_NAME : "Error while validating the name."
  NAME_REQUIRED : "The name field is required."

USER_GROUP:
  USER_GROUP_NAME_REQUIRED : "User group name is required."
  DUPLICATE_USER_GROUP_NAME : "A user group with the name '%1$s' already exists."
  USER_GROUP_DELETE_NOT_ALLOWED : "Deletion of user group '%1$s' is not allowed."

RESOURCE:
    RESOURCE_NAME_REQUIRED : "Resource name is required."
    RESOURCE_ACTION_REQUIRED : "Resource action URL is required."
    DUPLICATE_RESOURCE_NAME : "A resource with the name '%1$s' already exists."
    INVALID_PARENT_RESOURCE : "A child resource cannot have a child as its parent resource."

MODULE:
  MODULE_NAME_REQUIRED : "Module name is required."
  MODULE_ACTION_REQUIRED : "Module action URL is required."
  DUPLICATE_MODULE_NAME : "A module with the name '%1$s' already exists."
  SELECT_ACTION_OR_RESOURCE : "Please add either an action or select at least one resource for the module — not both."

ROLE:
  ROLE_NAME_REQUIRED : "Role name is required."
  DUPLICATE_ROLE_NAME : "A role with the name '%1$s' already exists."

APP_USER:
  USER_ID_REQUIRED : "User ID is required."
  EMAIL_REQUIRED : "Email is required."
  FIRST_NAME_REQUIRED : "First name is required."
  DUPLICATE_USER_ID: "A user with the ID '%1$s' already exists."
  EMAIL_IN_USE : "The email '%1$s' is already associated with another account."

USER_ROLE:
  APP_USER_ID_REQUIRED : "App user ID is required."
  ROLE_ID_REQUIRED : "Role ID is required."
  USER_GROUP_ID_REQUIRED : "User group ID is required."
  USER_ROLE_ALREADY_EXISTS : "The role already exists for the user in the specified user group."

USER_MODULES:
  USER_NOT_FOUND: "We couldn’t find an account with that user ID : '%1$s'. Please check and try again."
  ROLE_CANNOT_BE_NULL : "Role cannot be null. Please select a valid role for the user."
  ROLE_NOT_FOUND : "Please select a valid role for the user."
  PASSWORD_CANNOT_BE_EMPTY: "Password cannot be empty. Please enter a valid password."
  INCORRECT_PASSWORD: "The password you entered is incorrect. Please try again or reset your password."
  USER_ID_OR_PASSWORD_INCORRECT: "Invalid user ID or password. Please check your credentials and try again."
  ACCOUNT_DISABLED : "Your account has been disabled. Please contact administrator for assistance."
  ACCOUNT_LOCKED: "Your account has been locked,Please contact administrator for assistance."
  PASSWORD_EXPIRED: "Your password has expired. Please reset your password to continue."
  USER_NOT_AUTHORIZED : "You do not have the necessary permissions to access this resource."
  ROLE_NOT_SELECTED : "No role has been selected for the user. Please select a role to proceed."
  LOGOUT_SUCCESS : "You have been successfully logged out."
  PASSWORD_RESET_INITIATED : "A password reset link has been sent to your registered email address."
  INVALID_RESET_TOKEN: "The password reset token is invalid."
  RESET_TOKEN_EXPIRED: "The password reset token has expired."
  PASSWORD_RESET_SUCCESS: "Your password has been successfully reset. You can now log in with your new password."

ACADEMIC_YEAR:
    ACADEMIC_YEAR_CODE_REQUIRED : "Academic year code is required."
    ACADEMIC_YEAR_NAME_REQUIRED : "Academic year name is required."
    ACADEMIC_YEAR_DATE_CONFLICT : "The academic year '%1$s' has date conflicts with another academic year. Please adjust the dates to avoid overlap."
